name: POC-GITHUB-AWS-INTEGRATION

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-1
  
permissions:
  contents: read
  id-token: write   # <-- required for OIDC
  actions: read     # optional

jobs:
  deploy:
    name: Read S3
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<YOUR_ROLE_NAME>
        aws-region: ${{ env.AWS_REGION }}

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: List S3 buckets
      run: |
        aws s3 ls
